scss:
  enabled: false
eslint:
  enabled: true
  config_file: .eslintrc
ignore_file: .eslintignore
fail_on_violaions: true
ignore_file: public/emoji/css/cover.scss
ignore_file: public/emoji/css/cover.css
ignore_file: public/emoji/lib/js/emoji-picker.coffee